#!/usr/bin/env python3.4

def generate_enum(type_list):
    code = """
/*
** Code generated by ECSess in c++11
*/
    
enum class ComponentsTypes {
"""
    for i, t in enumerate(type_list):
        code += "\t" + t + " = " + str(i) + ("," if i < len(type_list) else "") + "\n"
        
    code += "};"
    return code


print(generate_enum(["CollideBox", "SpriteComp", "CoordComp"]))
